### ISSUE TITLE
Add option to use "simple" links, rather than full paths

### ISSUE THREAD

**Issue by barryvan** [Ebonsignori/obsidian-at-symbol-linking#4]
At present, when you use @-mentions, the links that are generated contain the full path and file extension -- for example, `[[Contacts/External/Barry van Oudtshoorn.md]]`. However, if one uses Obsidian's normal linking, the path is only included if it's ambiguous -- so in 99.9% of cases, that link would simply be `[[Barry van Oudtshoorn]]`.

It would be great if links inserted by this plugin could use the same logic that Obsidian uses. I'm not sure if perhaps there's a function in Obsidian to "simplify" links that could be called when selecting the file..?

**Comment by Ebonsignori** [comment]
Good catch! I went with the lazy fix of surrounding the markdown link with `<>` to account for spaces, but found a built in method to generate markdown links like you suggested. [Fixed in v1.1.5](https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.1.5)

Closing this for now, if you think more needs to be done feel free to reopen or create another issue if it doesn't let you

**Comment by Ebonsignori** [comment]
Good find! It looks like Obsidian will always assume link is to an `.md`, so it's safe to remove the `.md` when linking to an `.md` file.

Going to close this, but if you run into any more difficulties with it feel free to reopen or create a new issue for this
