### ISSUE TITLE
Feature request: create person note in selected directory if no person found

### ISSUE THREAD

**Issue by califa** [Ebonsignori/obsidian-at-symbol-linking#6]
Hey, love the plugin!

I'm currently using QuickAdd to add people notes via a template and then going back to link them in the origina file, but being able to do it inline would be truly amazing.

**Comment by Ebonsignori** [comment]
Hey @califa thank you! 

I'm not 100% sure I understand. I've two ideas:

1. You'd like me to add support for interfacing with the QuickAdd plugin
2. You'd like to have a new feature that is _like_ QuickAdd where if there isn't a matching person when you type @somename you get an option that might say "Create new note for somename" from the popup dropdown. Pressing enter/clicking the option creates the note for `somename`?

I like `#2` and would certainly implement it because it's something I'd use too, but the settings would probably be more limited than what QuickAdd allows.

Like you can set the template and directory that the "Create new", but there is only 1 template and 1 directory if that makes sense. 

For example adding this feature might the the following settings:

## Create new note
_If an @link isn't found, create a new note from template in directory_
1. Enable create new option: true/false
1. Create new note from template: `templates/person.md` (configurable)
2. Create new note in directory: `People/` (configurable)

Would this solve your use case?

**Comment by califa** [comment]
Yep exactly that, thank you!

**Comment by Ebonsignori** [comment]
Awesome, added it in the [latest release](https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.2.0) you can update to it from the `Community plugins` tab.

Please me know if you run into any bugs!

**Comment by califa** [comment]
Thank you, this is great!

Couple things:
- When I type in a name and press return, it adds a newline and messed up the link like:
[[name
|@name
]]
- I keep most of my people cards as full names—would be great if this didn't close on space (Either second or third space, or until I press escape maybe?)

Thank you!

**Comment by Ebonsignori** [comment]
Tracking in other issues

**Comment by Ebonsignori** [comment]
@califa fixed the newline issue and added a config to allow the popup to stay open for `X` spaces. Again, let me know if you run into any issues!

**Comment by califa** [comment]
This works perfectly. Thank you!
